### ISSUE TITLE
No Model selected

### ISSUE THREAD

**Issue by white-gecko** [AKSW/site.ontowiki#1]
When I first enable site extension I get following Error:

OntoWiki Error
No model pre-selected model, no parameter m (model) and no configured site model!

OntoWiki_Exception
/home/natanael/public_html/ontowiki/extensions/site/SiteController.php@190
#0: SiteController->_loadModel@90
#1: SiteController->__call@515
#2: Zend_Controller_Action->dispatch@295
#3: Zend_Controller_Dispatcher_Standard->dispatch@954
#4: Zend_Controller_Front->dispatch@97
#5: Zend_Application_Bootstrap_Bootstrap->run@366
#6: Zend_Application->run@157

**Comment by seebi** [comment]
what do you suggest here?
(the site extension can't be used without proper configuration)

I know its not documented yet :-)

**Comment by white-gecko** [comment]
I will add a warning, which tells the user to setup a proper 
configuration. This issue is more like a note for me to know what to 
take care of in the setup guide.

**Comment by white-gecko** [comment]
Closed by 16076541ddacd7d5211be4582d107b84636a5759
