### ISSUE TITLE
site project: schema publication

### ISSUE THREAD

**Issue by seebi** [AKSW/site.ontowiki#10]
Hi nate, for our different schemata we need a schema site implementation to allow for publication of classes, properties etc. A good starter for layout is 
- http://xmlns.com/foaf/spec/
  or
- http://vocab.deri.ie/void

Also we should verify our site implementation with [swbp-vocab-pub](http://www.w3.org/TR/swbp-vocab-pub/).

**Comment by white-gecko** [comment]
In the [schemaSite branch](https://github.com/AKSW/site.ontowiki/tree/feature/schemaSite) you can find the site as it is.

**Comment by seebi** [comment]
Is there a reason not to merge it in?

**Comment by white-gecko** [comment]
Done
