### ISSUE TITLE
literal helper: allow more then one output (multi value)

### ISSUE THREAD

**Issue by seebi** [AKSW/site.ontowiki#21]

**Comment by kkda** [comment]
Something like this? https://github.com/AKSW/site.ontowiki/commit/d41e3e5b36533ef7cf0247865b351ca540f9ea5b

We can add an option to return concatenated string instead of array here, which may also set array && !plain options by default.

**Comment by kkda** [comment]
Please, explain how exactly you want that to work.

**Comment by seebi** [comment]
yes, something like "output = first | all" with first as default is fine.
@haschek: any more reqs here? you have to use it :-)

**Comment by haschek** [comment]
We need that to simplify output commands, currently we have to use array/plain configurations and processing the returned array data in the template with for(each) commands and subtemplates. It would be easier to have an literal helper to concenate multiple values of a property with only one command.

I would suggest "foreach" as name of the new parameter, with false|true as possible values. We propably should add another paramter to configure separation output between the single literal outputs.

I personal would even prefer not to use a new "foreach" paramter on the literal method but instead a new literals method that is using the literal method. Probably easier to maintain and better readable code. This literals method can have all configuration of literal method plus the separation parameter.

**Comment by seebi** [comment]
ok, sounds good for me

**Comment by white-gecko** [comment]
Isn't this, want the querylist helper does?

**Comment by kkda** [comment]
querylist currently expects some sparql query (not just a property name) and a template to display query results (it does not provide any markup or output by itself).

**Comment by kkda** [comment]
We don't really need new arguments for `literal` helper, if we intend new `literals` helper to be used in this case.
