### ISSUE TITLE
extend template option class

### ISSUE THREAD

**Issue by seebi** [AKSW/site.ontowiki#27]
please have a look at
https://github.com/AKSW/site.ontowiki/blob/develop/schema/schema.ttl#L67

```
site:fetchOptionsFrom a owl:ObjectProperty, owl:TransitiveProperty;
  rdfs:comment "Instead (and in addition) of using TemplateOption properties directly, one can link to another resource to use the values from this resource. This allows for managing different options profiles and switch them easily.";
```

can you add this feature and document it at 
https://github.com/AKSW/site.ontowiki/wiki/Template-and-Site-Options

Please also document the behavior of comma separated values there.

In ESP we use this in combination with esp:Profile resources

**Comment by kkda** [comment]
Should options from linked resource's corresponding class and dataset be included, or only from the linked resource?

**Comment by seebi** [comment]
classes and datasets as well - this means, we have a 6 level hierarchy here.
1. attributes from linked resources on the dataset, will be overwritten by
2. direct attributes from the dataset, will be overwritten by
3. attributes from linked resources on the class, will be overwritten by
4. direct attributes from the class, will be overwritten by
5. attributes from linked resources on the current resource, will be overwritten by
6. direct attributes on the current resource

This sounds very much complicated for me.
Please minimize the query overhead here (in a cache-able way).

**Comment by kkda** [comment]
https://github.com/AKSW/site.ontowiki/commit/32e45f614242626a20b27e53c00366bbd06a9141
