### ISSUE TITLE
Back to Site for URIs outside the current Namespace

### ISSUE THREAD

**Issue by white-gecko** [AKSW/site.ontowiki#36]
The Back to Site Button should direct to <ontowiki base>/site/local/?r=<url encoded URI> if the resource is not in the <ontowiki base> namespace.

**Comment by kkda** [comment]
Like this? https://github.com/kkda/site.ontowiki/commit/12a84d0209c0250937225ac95e48dc0f37aaf7f9

**Comment by white-gecko** [comment]
Thank you, yes like this. But I would also like to have the URIs, which are in the namespace to end up as before.

```
http://aksw.org/Person1 -> http://aksw.org/Person1.html
http://ext.server.org/resource -> http://aksw.org/site/local/?r=http%3A%2F%2Fext.server.org%2Fresource
```

**Comment by white-gecko** [comment]
Do you like this? https://github.com/AKSW/site.ontowiki/commit/2cfbc90329d2fb9972c958b3edf11d07d0014e4b

**Comment by kkda** [comment]
It will work.

We must include ".html" here? URL is used just for the button, and site extension redirects to ".html" anyway, so I dropped that in my patch.

**Comment by white-gecko** [comment]
Hm, I think it is ok to explicitly redirect to the HTML version, using the '.html' (we can safe one redirect ;-) )
