### ISSUE TITLE
href/content attribute of link/meta elements contain wrong values

### ISSUE THREAD

**Issue by haschek** [AKSW/site.ontowiki#42]
I just see that meta and link elements are filled with wrong values for the content and href attributes, e.g. `<meta content="http://schema.org/ratingValue" itemprop="http://schema.org/ratingValue">` instead of `<meta content="4" itemprop="http://schema.org/ratingValue">`.

I found out that this bug was introduced by commit 3b94bc67dd5999eb45723dae8edf013c8070aa0f.

@kkda can you fix this asap please, a correct function is very important here.

**Comment by kkda** [comment]
Fixed in https://github.com/AKSW/site.ontowiki/commit/355271308317c177ea534e66c6d617d3c0c5ad54.
