### ISSUE TITLE
Using LinkHelper triggers PHP notice in Zend

### ISSUE THREAD

**Issue by haschek** [AKSW/site.ontowiki#47]
see https://github.com/AKSW/site.ontowiki/commit/d4e88306256befe6daaaa2defad4a2a17521bb6b#commitcomment-9263778

The change on rev d4e88306256befe6daaaa2defad4a2a17521bb6b introduces a bug, the PHP notice disapears if the link helper is used with parameter direct=true, but then it doesn't generate .html links (it's linking the resource URI directly).

**Comment by haschek** [comment]
@white-gecko I'm going to fix it now, send you a ull request later.

**Comment by white-gecko** [comment]
Are you using Zend version 1.12.9? I currently can't reproduce this issue.
