### ISSUE TITLE
how do we allow to create 301 Moved Permanently redirects 

### ISSUE THREAD

**Issue by seebi** [AKSW/site.ontowiki#7]
e.g. at aksw.org when we hard delete a project and want to redirect to a descendant project ...

@white-gecko any ideas?

**Comment by white-gecko** [comment]
Maybe a property `aksw:movedTo` (`rdfs:subPropertyOf rdfs:seeAlso`) and a redirect extension which sends the HTTP code and location in the header but still outputs the resource content (e.g. rdf) in the body.

**Comment by white-gecko** [comment]
Maybe an extension is overkill and we should just add a method to the SiteHelper which is listening to the right event and checks if a `aksw:movedTo` is specified.

Those are the events I could find so far: https://github.com/AKSW/OntoWiki/wiki/Events

**Comment by seebi** [comment]
implemented as site:MovedResource feature ...
